name: Command was dispatched
on:
  repository_dispatch:
    types: [echo-command]

jobs:
  commandDispatched:
    runs-on: ubuntu-latest
    steps:
      - name: Want something to say
        run: |
          echo "I've been dispatched"
      - name: Output command and arguments
        run: |
          echo "Command: ${{ github.event.client_payload.slash_command.command }}"
          echo "All named Args: ${{ github.event.client_payload.slash_command.args.all }}"
          echo "All unnamed Args: ${{ github.event.client_payload.slash_command.args.unnamed.all }}"
