name: Command was dispatched
on:
  repository_dispatch:
    types: [echo-command]

jobs:
  commandDispatched:
    runs-on: ubuntu-latest
    steps:
      - name: Want something to say
        run: |
          echo "I've been dispatched"
      - name: Output command and arguments
        run: |
          echo ${{ github.event.client_payload.slash_command.command }}
          echo ${{ github.event.client_payload.slash_command.args.all }}
          echo "Those are the arguments : ${{ github.event.client_payload.slash_command.args.unnamed.all }}"
